// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var sum = [0];

for(var num = 1; num <= 999; ++num){
  var match = +(num % 3 === 0 || num % 5 === 0);
  if (match !== 0) {
    sum[0] = sum[0] + num | 0;
  }
  
}

console.log(sum[0]);

exports.sum = sum;
/*  Not a pure module */
