// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var sum = [0];

for(var num = 1; num <= 999; ++num){
  if (num % 3 === 0) {
    sum[0] = sum[0] + num | 0;
  } else if (num % 5 === 0) {
    sum[0] = sum[0] + num | 0;
  }
  
}

Pervasives.print_int(sum[0]);

exports.sum = sum;
/*  Not a pure module */
