// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var sum = [0];

function isFizzy(num) {
  if (num % 3 === 0) {
    return /* Some */[num];
  } else if (num % 5 === 0) {
    return /* Some */[num];
  } else {
    return /* None */0;
  }
}

for(var num = 1; num <= 999; ++num){
  var match = isFizzy(num);
  if (match) {
    sum[0] = sum[0] + match[0] | 0;
  }
  
}

Pervasives.print_int(sum[0]);

exports.sum = sum;
exports.isFizzy = isFizzy;
/*  Not a pure module */
