// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var x = [0];

var y = [1];

function getNext() {
  var next = x[0] + y[0] | 0;
  x[0] = y[0];
  y[0] = next;
  return next;
}

var Fib = /* module */[
  /* x */x,
  /* y */y,
  /* getNext */getNext
];

function loop(_sum, _fib) {
  while(true) {
    var fib = _fib;
    var sum = _sum;
    if (fib > 4000000) {
      return sum;
    } else {
      _fib = getNext(/* () */0);
      if (fib % 2 === 0) {
        _sum = sum + fib | 0;
        continue ;
        
      } else {
        continue ;
        
      }
    }
  };
}

console.log(loop(0, getNext(/* () */0)));

exports.Fib = Fib;
exports.loop = loop;
/*  Not a pure module */
