// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function isFizzy(num) {
  if (num % 3 === 0) {
    return /* true */1;
  } else {
    return +(num % 5 === 0);
  }
}

function loop(_sum, _counter) {
  while(true) {
    var counter = _counter;
    var sum = _sum;
    if (counter === 1000) {
      return sum;
    } else {
      var match = isFizzy(counter);
      _counter = counter + 1 | 0;
      if (match !== 0) {
        _sum = sum + counter | 0;
        continue ;
        
      } else {
        continue ;
        
      }
    }
  };
}

console.log(loop(0, 1));

var stop = 1000;

exports.stop = stop;
exports.isFizzy = isFizzy;
exports.loop = loop;
/*  Not a pure module */
