// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function sum(list) {
  if (list) {
    return list[0] + sum(list[1]) | 0;
  } else {
    return 0;
  }
}

function isFizzy(num) {
  if (num % 3 === 0) {
    return /* true */1;
  } else {
    return +(num % 5 === 0);
  }
}

function fizz35(_list, _num) {
  while(true) {
    var num = _num;
    var list = _list;
    if (num !== 1000) {
      var match = isFizzy(num);
      _num = num + 1 | 0;
      if (match !== 0) {
        _list = /* :: */[
          num,
          list
        ];
        continue ;
        
      } else {
        continue ;
        
      }
    } else {
      return list;
    }
  };
}

console.log(sum(fizz35(/* [] */0, 1)));

exports.sum = sum;
exports.isFizzy = isFizzy;
exports.fizz35 = fizz35;
/*  Not a pure module */
